services:
  backend:
    build:
      context: ./backend
    container_name: antarctic-weather-api
    ports:
      - "8001:8000"
    volumes:
      - weather_data:/app/data
    env_file:
      - ./backend/.env

volumes:
  weather_data: